var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                    o             xxx         p ",
   "                                                   xxxx          xx!xx       xxx",
   "                                             xx                  x!!!x          ",
   "                          o                  xx                  x!!!xxx        ",
   "                        xxxxx           xxxxxx                   xxvxx          ",
   "    o                   x   x!!!!!!!!!!!x   xxxxxxxxxxxxxxxx                    ",
   "  xxxxx                 x   xxxxvxxxxxxxx                                    o  ",
   "  x                f    o                                                   xxxx",
   "  x            xxxxxx                       xxxxx                             x ",
   "  x          xxxx       o                                        xxxxx        x ",
   "  x  @       x      h                         h                  x   x!!!!!!!!x ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxx ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                  xxxxxxx                                    x!x  ",
   "                                                               xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                    f                 xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "               xxxxxxxxxxxx            xxxxxxxxxx!!x        x                                    o   o   o  x!x  ",
   "   o                                            xx!xxxxx     x     o   o                                    xx!x  ",
   "  xxxx                                           x!!!!!x     x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xxxxxvx     x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "           o                                                  xx!!!!!!!!!!!xx            v                        ",
   "   xxxx                                                        xxxx!!!!!xxxx      p                               ",
   "      xxxx                                     x     x            xxxxxxx        xxx         xxx                 ",
   "                                               x     x                           x x         x x                  ",
   "    o                                          x     x                             x         x                    ",
   "   xxxx                                        x     x                             xx        x                    ",
   "           xx                                  xx    x                             x         x                    ",
   "                               h               x     x      o  o     x   x         x       xxx                    ",
   "               xx!!xxx        xxx   xxxxxxxxxxxx     x               x   x         x         x                    ",
   "              xxxxxxxxx         x o x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "                                    x          x    xx               x   x   x               x                    ",
   "     @                 o    =       x          x     x               x   x   x               x                    ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x           x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],


  ["                                                                                                                  ",
   "                                            o               x                    o o o                            ",
   "     @                            xxxxxxxxxxxxxxxxxx        x                   xxxxxxx                           ",
   "     o           o                x                         xx                                       h            ",
   "     o      xxxxxxxxxxx           x                         xx            xxxxx                                   ",
   "     o      x    f               xx                                                                               ",
   "            x                     x          =                                                       p            ",
   "  xxxxxxxxxxx!!!xxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxx"],


  ["                                                                                                        x  ",
   "                                                                                                        x  ",
   "                                                                                                        x  ",
   "                                                                          xx        xxxxx               x  ",
   "                                                                                    x                   x  ",
   "                                                                                   xx                   x  ",
   "                                     !!!!!!                                         x                   x  ",
   "                        x            !vvvv!            x                            x           p       x  ",
   "                        x!!!!!!!!!!!!!    !!!!!!!!!!!!!x                    xxxxxxxxx                   x  ",
   "                        xxxxxxxxxxxxxx    xxxxxxxxxxxxxx                    x                           x  ",
   "                                                                    xx     xx                           x  ",
   "                                       o                                   x                            x  ",
   "  x                           o                  o     xxxxxxxxxx          x                            x  ",
   "  x                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                x  ",
   "  x               xxxx                                                                                  x  ",
   "  x                                             o                                               x       x  ",
   "  x       @                                     o                                              x!x      x  ",
   "  x    xxxxxxx                                  o                                             x!!!x     x  ",
   "  x                                                                                          x!!!!!x    x  ",
   "  x                 h                                                                       x!!!!!!!x   x  ",
   "  x        f                   xxxxxxxxxx   x     xxxxxxx      xxx                         xxxxx!xxxxx  x  ",
   "  x                            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                             x!x      x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxx"],

   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                x     x    xxxxxxxxx    x        x                              ",
    "                x     x    x       x    x        x                              ",
    "                x     x    x       x    x        x                              ",
    "                xxxxxxx    x       x    x        x                              ",
    "                   x       x       x    x        x                              ",
    "                   x       x       x    x        x                              ",
    "                   x       xxxxxxxxx    xxxxxxxxxx                              ",
    "                                                                                ",
    "                    x           x    x    x      x                              ",
    "                    x     x     x    x    x x    x                              ",
    "                    x     x     x    x    x  x   x                              ",
    "                    x     x     x    x    x   x  x                              ",
    "                    x     x     x    x    x    x x                              ",
    "    @               xxxxxxxxxxxxx    x    x     xx                              ",
    "                                                                                ",
    "                                                                                ",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                "]
  ];


if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
